.\" Manpage for albumfs.
.TH ALBUMFS 1 "Dec 2015" "0.1.3" "User Commands"
.SH NAME
albumfs \- key encrypted LSB steganography PNG album filesystem in userspace
.SH SYNOPSIS
albumfs [OPTIONS]... [PATH/TO/ROOTIMAGE.PNG]
.SH DESCRIPTION
Create, access, and modify a LSB steganography filesystem in userspace using a directory of PNG images.  Filesystem state is only preserved after safely closing the filesystem via unmount or Ctrl+C.  A filesystem may only use images with the same dimensions as the root image provided.
.PP
A filesystem requires a name, key, root image, and storage images.  To access a filesystem the correct key, filesystem name, and root image must be given.  All data is XOR'd with the key as it is read and written from the images.  The root image stores the filesystem name, consumed and total space, image and file count, image filenames, and file meta data.  All images added to the filesystem while formatting or expanding are found in the same directory as the root image.
.PP
Formatting a filesystem wipes each avialable least signifigant bit in the images provided, similarly removing a file wipes its imprint and shifts the filesystem if there is a hole.  All files in the filesystem have permissions of 644 and cannot be edited, but can be read, renamed, deleted, and copied.
.TP
.B -format
create a new filesystem using valid images in directory of root image provided and mount it.
.TP
.B -expand
expand and mount an existing filesystem. The directory containing the root image is scanned for additional valid PNG images not already included in the filesystem. 
.TP
.B -mount
mount an existing filesystem 
.TP
.B -debug
enable bit by bit debug output. IO blocking from this output will cause the filesystem to operate very slowly.
.TP
.B -help
echo command syntax and exit program.
.SH EXAMPLES
.PP
albumfs -format images/vacation/image.png
.PP
albumfs -debug -mount images/vacation/image.png
.SH SEE ALSO
fuse(8)
.SH AUTHOR
albumfs is developed by Michael Geitz <mrgeitz@gmail.com>
